version: '3.8'

services:
  api-gateway:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-api-gateway:latest
    build: null

  auth-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-auth-service:latest
    build: null

  academy-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-academy-service:latest
    build: null

  con-tech-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-con-tech-service:latest
    build: null

  events-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-events-service:latest
    build: null

  careers-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-careers-service:latest
    build: null

  file-upload-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-file-upload-service:latest
    build: null

  home-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-home-service:latest
    build: null

  home-frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alikohub-home-frontend:latest
    build: null
