import { IsEnum, IsNotEmpty } from 'class-validator';
import { ContractStatus } from '../../generated/client'; // Import the enum generated by Prisma

export class UpdateContractStatusDto {
  @IsEnum(ContractStatus)
  @IsNotEmpty()
  status: ContractStatus;
}
