apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alikohub

resources:
  - namespace.yaml
  - secrets.yaml
  - auth-service.yaml
  - domain-services.yaml
  - api-gateway.yaml

commonLabels:
  project: alikohub
