apiVersion: v1
kind: Secret
metadata:
  name: alikohub-secrets
  namespace: alikohub
type: Opaque
stringData:
  auth-db-url: "postgresql://auth_user:auth_pass@postgres-auth:5432/authdb"
  contech-db-url: "postgresql://contech_user:contech_pass@postgres-contech:5432/contechdb"
  academy-db-url: "postgresql://academy_user:academy_pass@postgres-academy:5432/academydb"
  events-db-url: "postgresql://events_user:events_pass@postgres-events:5432/eventsdb"
