import type { Course } from "./components/types.d.jsx";

export const courses: Course[] = [
  {
    id: 1,
    title: "Full-Stack Web Development",
    longDescription:
      "This comprehensive course is designed to guide you from the fundamentals of web development to deploying a complete, production-ready application. \n    \n    You'll begin by learning HTML, CSS, and JavaScript basics before diving deep into React for building interactive UIs. We’ll explore functional components, hooks, and efficient state management techniques, ensuring you can create scalable, maintainable frontend code.\n    \n    Next, you’ll transition to backend development with Node.js and Express.js, where you’ll learn to design RESTful APIs, handle authentication and authorization, and connect your application to MongoDB for dynamic data storage. We’ll cover best practices for error handling, security, and performance optimization.\nFinally, you’ll deploy your full-stack application to a cloud hosting service, integrate CI/CD workflows, and gain experience with version control using Git. By the end of this course, you’ll have built a polished, professional-grade project for your portfolio.",
    shortDescription:
      "Build and deploy modern web apps using React, Node.js, and MongoDB.",
    category: "Technology",
    subCategory: "Web Development",
    instructorId: "instructor-1",
    status: "PUBLISHED",
    skills: [
      "React",
      "Node.js",
      "MongoDB",
      "REST APIs",
      "Express.js",
      "Deployment",
    ],
    conceptsLearned: [
      "Component-based architecture",
      "State management",
      "CRUD operations",
      "Authentication & Authorization",
      "API integration",
    ],
    estimatedTime: 40,
    targetLevel: "Intermediate",
    enrolledNum: 1520,
    rating: 4.8,
    price: 129.99,
    prerequisites: ["Basic HTML", "Basic JavaScript"],
    languages: ["English", "Spanish"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 1,
      firebaseId: "firebase-1",
      firstname: "Sarah",
      lastname: "Mitchell",
      email: "sarah.mitchell@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 2,
    title: "Python for Data Science",
    longDescription:
      "Whether you're completely new to programming or looking to sharpen your skills for a career in data science, this course offers a structured, practical approach to mastering Python in the context of data analysis. \nWe’ll start with Python syntax, data types, and control flow before moving into powerful libraries such as NumPy for numerical computing and Pandas for data manipulation.\n\nYou’ll gain hands-on experience with real-world datasets, learning to clean and preprocess messy data, perform exploratory data analysis, and generate clear, insightful visualizations using Matplotlib and Seaborn. Once you’re comfortable with the data pipeline, we’ll introduce you to the fundamentals of machine learning with scikit-learn — covering model training, testing, and evaluation.\n\nBy the end of the course, you’ll have a portfolio of mini-projects, including data dashboards, analytical reports, and predictive models, ready to showcase your skills to potential employers.",
    shortDescription:
      "Learn Python and data analysis tools to kickstart your data science career.",
    category: "STEM",
    subCategory: "Data Science",
    instructorId: "instructor-2",
    status: "PUBLISHED",
    skills: ["Python", "Pandas", "NumPy", "Matplotlib", "Scikit-learn"],
    conceptsLearned: [
      "Data cleaning",
      "Exploratory data analysis",
      "Model training & evaluation",
      "Visualization techniques",
    ],
    estimatedTime: 30,
    targetLevel: "Beginner",
    enrolledNum: 2980,
    rating: 4.7,
    price: 99.99,
    prerequisites: ["Basic Computer Skills"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 2,
      firebaseId: "firebase-2",
      firstname: "David",
      lastname: "Kim",
      email: "david.kim@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals",
    longDescription:
      "In this beginner-friendly course, you’ll discover how great design impacts the way users interact with technology. We’ll start with the principles of design thinking — understanding your users, defining their needs, and ideating creative solutions. \nFrom there, you’ll learn how to create user personas, build wireframes, and develop clickable prototypes using Figma.\n\nWe’ll explore visual design fundamentals, including color theory, typography, and layout composition, while also diving into usability best practices to ensure your designs are intuitive and accessible. The course emphasizes real-world projects, allowing you to design mobile and web interfaces that are both beautiful and functional.\n\nBy the end of the program, you’ll have a complete design case study — from research to final prototype — which you can add to your portfolio to demonstrate your skills to potential clients or employers.",
    shortDescription:
      "Master the principles of user interface and user experience design.",
    category: "Technology",
    subCategory: "Design",
    instructorId: "instructor-3",
    status: "PUBLISHED",
    skills: ["UI Design", "UX Research", "Prototyping", "Wireframing", "Figma"],
    conceptsLearned: [
      "Color theory",
      "Typography",
      "User personas",
      "Interactive prototyping",
      "Accessibility",
    ],
    estimatedTime: 25,
    targetLevel: "Beginner",
    enrolledNum: 870,
    rating: 4.6,
    price: 79.99,
    prerequisites: ["Basic Computer Skills"],
    languages: ["English", "French"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 3,
      firebaseId: "firebase-3",
      firstname: "Emily",
      lastname: "Carter",
      email: "emily.carter@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 4,
    title: "Advanced Java Programming",
    longDescription:
      "This course is tailored for experienced Java developers who want to refine their skills and dive into the language’s more sophisticated capabilities. We’ll begin with a deep dive into the Streams API and functional programming techniques that allow for cleaner, more expressive code.\n\nYou’ll learn about Java concurrency and multithreading, mastering synchronization, thread safety, and parallel processing to build efficient, responsive applications. We’ll explore common design patterns such as Singleton, Builder, and Observer, discussing when and why to use each, along with practical examples.\n\nMemory management and garbage collection will be covered in detail, helping you diagnose and prevent performance bottlenecks. The course includes hands-on projects where you’ll build complex applications and implement advanced debugging and profiling techniques to ensure they run smoothly in production environments.",
    shortDescription:
      "Take your Java skills to the next level with advanced concepts and best practices.",
    category: "STEM",
    subCategory: "Programming",
    instructorId: "instructor-4",
    status: "PUBLISHED",
    skills: [
      "Java",
      "Concurrency",
      "Streams API",
      "Design Patterns",
      "Performance Optimization",
    ],
    conceptsLearned: [
      "Thread safety",
      "Functional programming in Java",
      "Observer pattern",
      "Builder pattern",
      "Garbage collection",
    ],
    estimatedTime: 35,
    targetLevel: "Advanced",
    enrolledNum: 460,
    rating: 4.9,
    price: 139.99,
    prerequisites: ["Java Basics"],
    languages: ["English", "German"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 4,
      firebaseId: "firebase-4",
      firstname: "Michael",
      lastname: "Brown",
      email: "michael.brown@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 5,
    title: "Cloud Computing with AWS",
    longDescription:
      "Cloud computing is transforming the way businesses operate, and AWS is at the forefront of this revolution. This course takes you through the essential AWS services and how to leverage them to build scalable, secure, and cost-effective cloud applications.\n\nWe’ll start with an overview of the AWS ecosystem before diving into core services like EC2 for computing power, S3 for object storage, and RDS for managed databases. You’ll gain practical experience creating and configuring these resources, as well as managing permissions and security with IAM.\n\nThe course also covers automation using AWS CloudFormation, allowing you to define infrastructure as code for consistent deployments. We’ll examine architectural best practices, cost optimization strategies, and disaster recovery planning. By the end, you’ll have the skills to confidently deploy production-grade applications in the AWS cloud.",
    shortDescription:
      "Learn how to design, deploy, and manage applications on Amazon Web Services.",
    category: "Technology",
    subCategory: "Cloud Computing",
    instructorId: "instructor-5",
    status: "PUBLISHED",
    skills: ["AWS", "CloudFormation", "EC2", "S3", "RDS", "IAM"],
    conceptsLearned: [
      "Scalable architecture",
      "Security best practices",
      "Automation with templates",
      "Database management in the cloud",
    ],
    estimatedTime: 28,
    targetLevel: "Intermediate",
    enrolledNum: 1120,
    rating: 4.8,
    price: 119.99,
    prerequisites: ["Basic Networking", "Linux Basics"],
    languages: ["English", "Japanese"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 5,
      firebaseId: "firebase-5",
      firstname: "Rachel",
      lastname: "Green",
      email: "rachel.green@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 6,
    title: "Machine Learning with TensorFlow",
    longDescription:
      "This course walks you through the foundations of machine learning, starting with supervised and unsupervised learning concepts, and moving towards deep learning with TensorFlow and Keras. You’ll work with image, text, and numeric data, creating models for classification, regression, and natural language processing.\n\nWe’ll cover neural network architectures, optimization techniques, and regularization methods to improve model accuracy. Practical projects include building a handwritten digit recognizer, a sentiment analysis model, and a recommendation system.\n\nBy the end of this course, you’ll be comfortable designing, training, and deploying machine learning models in real-world scenarios, both locally and in the cloud.",
    shortDescription:
      "Build and deploy machine learning models using TensorFlow and Keras.",
    category: "STEM",
    subCategory: "Artificial Intelligence",
    instructorId: "instructor-6",
    status: "PUBLISHED",
    skills: [
      "TensorFlow",
      "Keras",
      "Deep Learning",
      "Neural Networks",
      "Data Preprocessing",
    ],
    conceptsLearned: [
      "Gradient descent",
      "Overfitting prevention",
      "Convolutional layers",
      "Recurrent layers",
      "Model deployment",
    ],
    estimatedTime: 45,
    targetLevel: "Intermediate",
    enrolledNum: 890,
    rating: 4.7,
    price: 149.99,
    prerequisites: ["Python Basics", "Linear Algebra"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 6,
      firebaseId: "firebase-6",
      firstname: "Daniel",
      lastname: "Lee",
      email: "daniel.lee@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 7,
    title: "Cybersecurity Fundamentals",
    longDescription:
      "This course covers the essentials of cybersecurity, from understanding different types of threats to implementing practical security measures. You’ll learn about network security, encryption, firewalls, and intrusion detection systems.\n\nWe’ll also explore the principles of ethical hacking and penetration testing, giving you insight into how attackers operate and how to defend against them. Practical labs will have you configuring security tools, monitoring logs, and responding to simulated cyber incidents.\n\nBy the end, you’ll be able to assess risks, apply security best practices, and contribute to safeguarding an organization’s digital assets.",
    shortDescription:
      "Learn how to protect systems, networks, and data from cyber threats.",
    category: "STEM",
    subCategory: "Cybersecurity",
    instructorId: "instructor-7",
    status: "PUBLISHED",
    skills: [
      "Network Security",
      "Encryption",
      "Penetration Testing",
      "Incident Response",
      "Risk Assessment",
    ],
    conceptsLearned: [
      "CIA Triad",
      "Firewalls",
      "IDS/IPS",
      "Vulnerability scanning",
      "Security policies",
    ],
    estimatedTime: 35,
    targetLevel: "Intermediate",
    enrolledNum: 1040,
    rating: 4.8,
    price: 129.99,
    prerequisites: ["Basic Networking"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 7,
      firebaseId: "firebase-7",
      firstname: "Laura",
      lastname: "Thompson",
      email: "laura.thompson@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 8,
    title: "iOS App Development with Swift",
    longDescription:
      "Starting with the basics of Swift programming, this course takes you through building responsive, user-friendly iOS applications. You’ll work in Xcode to design interfaces, connect UI elements to code, and implement navigation and data persistence.\n\nWe’ll cover important topics like working with APIs, implementing animations, and optimizing for performance. The course includes projects such as a weather app, a task manager, and a photo-sharing app.\n\nBy the end, you’ll be ready to publish your own iOS app to the App Store.",
    shortDescription:
      "Design and build iOS apps from scratch using Swift and Xcode.",
    category: "Technology",
    subCategory: "Mobile Development",
    instructorId: "instructor-8",
    status: "PUBLISHED",
    skills: ["Swift", "Xcode", "UIKit", "Core Data", "REST APIs"],
    conceptsLearned: [
      "App lifecycle",
      "MVC pattern",
      "Data persistence",
      "API integration",
      "UI animations",
    ],
    estimatedTime: 40,
    targetLevel: "Intermediate",
    enrolledNum: 760,
    rating: 4.7,
    price: 139.99,
    prerequisites: ["Basic Programming Knowledge"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 8,
      firebaseId: "firebase-8",
      firstname: "Jonathan",
      lastname: "Reed",
      email: "jonathan.reed@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 9,
    title: "Android App Development with Kotlin",
    longDescription:
      "Learn to create Android apps using Kotlin, Google’s preferred language for Android development. You’ll set up Android Studio, design layouts with XML, and implement interactive features with Kotlin.\n\nWe’ll explore key Android concepts such as activity lifecycle, fragments, data storage, and networking. You’ll work on apps including a note-taking app, a news reader, and a fitness tracker.\n\nBy the end, you’ll have the skills to develop and deploy Android apps to the Google Play Store.",
    shortDescription:
      "Build Android applications using Kotlin and Android Studio.",
    category: "Technology",
    subCategory: "Mobile Development",
    instructorId: "instructor-9",
    status: "PUBLISHED",
    skills: ["Kotlin", "Android Studio", "XML", "SQLite", "Retrofit"],
    conceptsLearned: [
      "Activity lifecycle",
      "Fragments",
      "Local storage",
      "Networking",
      "App publishing",
    ],
    estimatedTime: 42,
    targetLevel: "Intermediate",
    enrolledNum: 820,
    rating: 4.8,
    price: 139.99,
    prerequisites: ["Basic Programming Knowledge"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 9,
      firebaseId: "firebase-9",
      firstname: "Sophia",
      lastname: "Martinez",
      email: "sophia.martinez@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 10,
    title: "DevOps with Docker and Kubernetes",
    longDescription:
      "This course takes you through the core concepts of containerization and orchestration. You’ll learn to create Docker images, manage containers, and deploy applications using Kubernetes clusters.\n\nWe’ll also cover CI/CD pipelines, infrastructure as code, and monitoring with tools like Prometheus and Grafana. Hands-on labs will guide you through deploying microservices and scaling them efficiently.\n\nBy the end, you’ll have practical DevOps skills to streamline software delivery and operations.",
    shortDescription:
      "Automate, deploy, and manage applications with Docker and Kubernetes.",
    category: "Technology",
    subCategory: "DevOps",
    instructorId: "instructor-10",
    status: "PUBLISHED",
    skills: [
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Infrastructure as Code",
      "Monitoring",
    ],
    conceptsLearned: [
      "Containerization",
      "Cluster management",
      "Load balancing",
      "Rolling updates",
      "Service discovery",
    ],
    estimatedTime: 38,
    targetLevel: "Intermediate",
    enrolledNum: 940,
    rating: 4.8,
    price: 149.99,
    prerequisites: ["Linux Basics", "Basic Networking"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 10,
      firebaseId: "firebase-10",
      firstname: "Mark",
      lastname: "Evans",
      email: "mark.evans@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 11,
    title: "Game Development with Unity",
    longDescription:
      "From game design principles to coding gameplay mechanics, this course teaches you how to develop interactive games using Unity. You’ll learn to create scenes, work with physics, implement animations, and design user interfaces.\n\nProjects include a 2D platformer, a first-person shooter, and a mobile puzzle game. We’ll also cover asset management and optimization for performance.\n\nBy the end, you’ll have a portfolio of games ready to showcase to potential employers or players.",
    shortDescription: "Create 2D and 3D games using Unity and C#.",
    category: "Technology",
    subCategory: "Game Development",
    instructorId: "instructor-11",
    status: "PUBLISHED",
    skills: ["Unity", "C#", "Physics", "Animation", "UI Design"],
    conceptsLearned: [
      "Game loop",
      "Collision detection",
      "Character controllers",
      "Level design",
      "Optimization",
    ],
    estimatedTime: 50,
    targetLevel: "Intermediate",
    enrolledNum: 670,
    rating: 4.7,
    price: 159.99,
    prerequisites: ["Basic Programming Knowledge"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 11,
      firebaseId: "firebase-11",
      firstname: "Olivia",
      lastname: "Parker",
      email: "olivia.parker@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 12,
    title: "Blockchain Development with Ethereum",
    longDescription:
      "This course covers blockchain fundamentals, Ethereum architecture, and smart contract development with Solidity. You’ll learn to create decentralized applications (dApps) and interact with the blockchain using Web3.js.\n\nProjects include a token creation app, a decentralized voting platform, and an NFT marketplace. Security considerations and gas optimization techniques are also covered.\n\nBy the end, you’ll be able to build, test, and deploy secure smart contracts on the Ethereum network.",
    shortDescription:
      "Build decentralized applications using Ethereum and Solidity.",
    category: "STEM",
    subCategory: "Blockchain",
    instructorId: "instructor-12",
    status: "PUBLISHED",
    skills: [
      "Blockchain",
      "Ethereum",
      "Solidity",
      "Web3.js",
      "Smart Contracts",
    ],
    conceptsLearned: [
      "Consensus mechanisms",
      "Smart contract security",
      "Gas optimization",
      "dApp architecture",
      "Token standards",
    ],
    estimatedTime: 48,
    targetLevel: "Advanced",
    enrolledNum: 560,
    rating: 4.8,
    price: 179.99,
    prerequisites: ["JavaScript Basics", "Basic Cryptography"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 12,
      firebaseId: "firebase-12",
      firstname: "Ethan",
      lastname: "Brooks",
      email: "ethan.brooks@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 13,
    title: "Data Visualization with D3.js",
    longDescription:
      "Learn to transform data into stunning visual representations using D3.js. This course covers data binding, scales, axes, transitions, and interactivity.\n\nProjects include bar charts, line graphs, scatter plots, and interactive maps. You’ll also learn best practices for storytelling with data and optimizing visualizations for performance.\n\nBy the end, you’ll be able to create engaging, interactive dashboards and reports.",
    shortDescription:
      "Create interactive, data-driven visualizations for the web using D3.js.",
    category: "STEM",
    subCategory: "Data Visualization",
    instructorId: "instructor-13",
    status: "PUBLISHED",
    skills: ["D3.js", "JavaScript", "SVG", "Data Binding", "Animation"],
    conceptsLearned: [
      "Scales and axes",
      "Data joins",
      "Transitions",
      "User interaction",
      "Responsive design",
    ],
    estimatedTime: 32,
    targetLevel: "Intermediate",
    enrolledNum: 740,
    rating: 4.7,
    price: 119.99,
    prerequisites: ["JavaScript Basics"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 13,
      firebaseId: "firebase-13",
      firstname: "Natalie",
      lastname: "Cooper",
      email: "natalie.cooper@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 14,
    title: "Full-Stack Web Development with React & Node.js",
    longDescription:
      "This comprehensive course is designed to guide you from the fundamentals of web development to deploying a complete, production-ready application.\nYou'll begin by learning HTML, CSS, and JavaScript basics before diving deep into React for building interactive UIs. We’ll explore functional components, hooks, and efficient state management techniques, ensuring you can create scalable, maintainable frontend code.\n\nNext, you’ll transition to backend development with Node.js and Express.js, where you’ll learn to design RESTful APIs, handle authentication and authorization, and connect your application to MongoDB for dynamic data storage. We’ll cover best practices for error handling, security, and performance optimization.\n\nFinally, you’ll deploy your full-stack application to a cloud hosting service, integrate CI/CD workflows, and gain experience with version control using Git. By the end of this course, you’ll have built a polished, professional-grade project for your portfolio.",
    shortDescription:
      "Build and deploy modern web apps using React, Node.js, and MongoDB.",
    category: "Technology",
    subCategory: "Web Development",
    instructorId: "instructor-14",
    status: "PUBLISHED",
    skills: [
      "React",
      "Node.js",
      "MongoDB",
      "REST APIs",
      "Express.js",
      "Deployment",
    ],
    conceptsLearned: [
      "Component-based architecture",
      "State management",
      "CRUD operations",
      "Authentication & Authorization",
      "API integration",
    ],
    estimatedTime: 40,
    targetLevel: "Intermediate",
    enrolledNum: 1520,
    rating: 4.8,
    price: 129.99,
    prerequisites: ["Basic HTML", "Basic JavaScript"],
    languages: ["English", "Spanish"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 14,
      firebaseId: "firebase-14",
      firstname: "Sarah",
      lastname: "Mitchell",
      email: "sarah.mitchell@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 15,
    title: "Python for Data Science",
    longDescription:
      "Whether you're completely new to programming or looking to sharpen your skills for a career in data science, this course offers a structured, practical approach to mastering Python in the context of data analysis.\nWe’ll start with Python syntax, data types, and control flow before moving into powerful libraries such as NumPy for numerical computing and Pandas for data manipulation.\n\nYou’ll gain hands-on experience with real-world datasets, learning to clean and preprocess messy data, perform exploratory data analysis, and generate clear, insightful visualizations using Matplotlib and Seaborn. Once you’re comfortable with the data pipeline, we’ll introduce you to the fundamentals of machine learning with scikit-learn — covering model training, testing, and evaluation.\n\nBy the end of the course, you’ll have a portfolio of mini-projects, including data dashboards, analytical reports, and predictive models, ready to showcase your skills to potential employers.",
    shortDescription:
      "Learn Python and data analysis tools to kickstart your data science career.",
    category: "STEM",
    subCategory: "Data Science",
    instructorId: "instructor-15",
    status: "PUBLISHED",
    skills: ["Python", "Pandas", "NumPy", "Matplotlib", "Scikit-learn"],
    conceptsLearned: [
      "Data cleaning",
      "Exploratory data analysis",
      "Model training & evaluation",
      "Visualization techniques",
    ],
    estimatedTime: 30,
    targetLevel: "Beginner",
    enrolledNum: 2980,
    rating: 4.7,
    price: 99.99,
    prerequisites: ["Basic Computer Skills"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      firebaseId: "firebase-15",
      firstname: "David",
      lastname: "Kim",
      email: "david.kim@example.com",
      globalRole: "USER",
      role: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 16,
    title: "UI/UX Design Fundamentals",
    longDescription:
      "In this beginner-friendly course, you’ll discover how great design impacts the way users interact with technology. We’ll start with the principles of design thinking — understanding your users, defining their needs, and ideating creative solutions.\nFrom there, you’ll learn how to create user personas, build wireframes, and develop clickable prototypes using Figma.\n\nWe’ll explore visual design fundamentals, including color theory, typography, and layout composition, while also diving into usability best practices to ensure your designs are intuitive and accessible. The course emphasizes real-world projects, allowing you to design mobile and web interfaces that are both beautiful and functional.\n\nBy the end, you’ll have a complete design case study — from research to final prototype — which you can add to your portfolio to demonstrate your skills to potential clients or employers.",
    shortDescription:
      "Master the principles of user interface and user experience design.",
    category: "STEM",
    subCategory: "Design",
    instructorId: "instructor-16",
    status: "PUBLISHED",
    skills: ["UI Design", "UX Research", "Prototyping", "Wireframing", "Figma"],
    conceptsLearned: [
      "Color theory",
      "Typography",
      "User personas",
      "Interactive prototyping",
      "Accessibility",
    ],
    estimatedTime: 25,
    targetLevel: "Beginner",
    enrolledNum: 870,
    rating: 4.6,
    price: 79.99,
    prerequisites: ["Basic Computer Skills"],
    languages: ["English", "French"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 16,
      firebaseId: "firebase-16",
      firstname: "Emily",
      lastname: "Carter",
      email: "emily.carter@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 17,
    title: "Advanced Java Programming",
    longDescription:
      "This course is tailored for experienced Java developers who want to refine their skills and dive into the language’s more sophisticated capabilities. We’ll begin with a deep dive into the Streams API and functional programming techniques that allow for cleaner, more expressive code.\n\nYou’ll learn about Java concurrency and multithreading, mastering synchronization, thread safety, and parallel processing to build efficient, responsive applications. We’ll explore common design patterns such as Singleton, Builder, and Observer, discussing when and why to use each, along with practical examples.\n\nMemory management and garbage collection will be covered in detail, helping you diagnose and prevent performance bottlenecks. The course includes hands-on projects where you’ll build complex applications and implement advanced debugging and profiling techniques to ensure they run smoothly in production environments.",
    shortDescription:
      "Take your Java skills to the next level with advanced concepts and best practices.",
    category: "STEM",
    subCategory: "Programming",
    instructorId: "instructor-17",
    status: "PUBLISHED",
    skills: [
      "Java",
      "Concurrency",
      "Streams API",
      "Design Patterns",
      "Performance Optimization",
    ],
    conceptsLearned: [
      "Thread safety",
      "Functional programming in Java",
      "Observer pattern",
      "Builder pattern",
      "Garbage collection",
    ],
    estimatedTime: 35,
    targetLevel: "Advanced",
    enrolledNum: 460,
    rating: 4.9,
    price: 139.99,
    prerequisites: ["Java Basics"],
    languages: ["English", "German"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 17,
      firebaseId: "firebase-17",
      firstname: "Michael",
      lastname: "Brown",
      email: "michael.brown@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 18,
    title: "Cloud Computing with AWS",
    longDescription:
      "Cloud computing is transforming the way businesses operate, and AWS is at the forefront of this revolution. This course takes you through the essential AWS services and how to leverage them to build scalable, secure, and cost-effective cloud applications.\n\nWe’ll start with an overview of the AWS ecosystem before diving into core services like EC2 for computing power, S3 for object storage, and RDS for managed databases. You’ll gain practical experience creating and configuring these resources, as well as managing permissions and security with IAM.\n\nThe course also covers automation using AWS CloudFormation, allowing you to define infrastructure as code for consistent deployments. We’ll examine architectural best practices, cost optimization strategies, and disaster recovery planning. By the end, you’ll have the skills to confidently deploy production-grade applications in the AWS cloud.",
    shortDescription:
      "Learn how to design, deploy, and manage applications on Amazon Web Services.",
    category: "Technology",
    subCategory: "Cloud Computing",
    instructorId: "instructor-18",
    status: "PUBLISHED",
    skills: ["AWS", "CloudFormation", "EC2", "S3", "RDS", "IAM"],
    conceptsLearned: [
      "Scalable architecture",
      "Security best practices",
      "Automation with templates",
      "Database management in the cloud",
    ],
    estimatedTime: 28,
    targetLevel: "Intermediate",
    enrolledNum: 1120,
    rating: 4.8,
    price: 119.99,
    prerequisites: ["Basic Networking", "Linux Basics"],
    languages: ["English", "Japanese"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 18,
      firebaseId: "firebase-18",
      firstname: "Rachel",
      lastname: "Green",
      email: "rachel.green@example.com",
      role: "INSTRUCTOR",
      globalRole: "USER",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 19,
    title: "Machine Learning with TensorFlow",
    longDescription:
      "This course walks you through the foundations of machine learning, starting with supervised and unsupervised learning concepts, and moving towards deep learning with TensorFlow and Keras. You’ll work with image, text, and numeric data, creating models for classification, regression, and natural language processing.\n\nWe’ll cover neural network architectures, optimization techniques, and regularization methods to improve model accuracy. Practical projects include building a handwritten digit recognizer, a sentiment analysis model, and a recommendation system.\n\nBy the end of this course, you’ll be comfortable designing, training, and deploying machine learning models in real-world scenarios, both locally and in the cloud.",
    shortDescription:
      "Build and deploy machine learning models using TensorFlow and Keras.",
    category: "STEM",
    subCategory: "Artificial Intelligence",
    instructorId: "instructor-19",
    status: "PUBLISHED",
    skills: [
      "TensorFlow",
      "Keras",
      "Deep Learning",
      "Neural Networks",
      "Data Preprocessing",
    ],
    conceptsLearned: [
      "Gradient descent",
      "Overfitting prevention",
      "Convolutional layers",
      "Recurrent layers",
      "Model deployment",
    ],
    estimatedTime: 45,
    targetLevel: "Intermediate",
    enrolledNum: 890,
    rating: 4.7,
    price: 149.99,
    prerequisites: ["Python Basics", "Linear Algebra"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 19,
      firebaseId: "firebase-19",
      firstname: "Daniel",
      lastname: "Lee",
      email: "daniel.lee@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 20,
    title: "Cybersecurity Fundamentals",
    longDescription:
      "This course introduces you to the core principles of cybersecurity, including risk management, encryption, network defense, and threat detection. You’ll explore different types of cyberattacks such as phishing, ransomware, and DDoS attacks, learning how to prevent and mitigate them.\n\nHands-on labs will guide you through configuring firewalls, setting up intrusion detection systems, and implementing multi-factor authentication. We’ll also cover legal and ethical considerations in cybersecurity, preparing you for both technical and compliance aspects of the field.\n\nBy the end, you’ll have the foundational skills to protect digital assets and respond effectively to security incidents.",
    shortDescription:
      "Learn the essentials of securing networks, systems, and applications.",
    category: "STEM",
    subCategory: "Cybersecurity",
    instructorId: "instructor-20",
    status: "PUBLISHED",
    skills: [
      "Network Security",
      "Encryption",
      "Threat Detection",
      "Incident Response",
      "Firewalls",
    ],
    conceptsLearned: [
      "CIA Triad",
      "Malware analysis",
      "Security policies",
      "Vulnerability scanning",
    ],
    estimatedTime: 32,
    targetLevel: "Beginner",
    enrolledNum: 780,
    rating: 4.6,
    price: 109.99,
    prerequisites: ["Basic Networking Knowledge"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 20,
      firebaseId: "firebase-20",
      firstname: "Laura",
      lastname: "Simmons",
      email: "laura.simmons@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
  {
    id: 21,
    title: "Digital Health & Wellness",
    longDescription:
      "Explore the intersection of technology and healthcare with this course on digital health and wellness. You’ll learn about wearable devices, mobile health apps, telemedicine platforms, and how data analytics is transforming patient care.\n\nTopics include privacy and security considerations in healthcare technology, designing user-centered health solutions, and evaluating digital tools for effectiveness. Hands-on projects include creating a wellness tracking app and developing patient engagement strategies.\n\nBy the end, you’ll have the knowledge to design, assess, and implement technology solutions that improve health outcomes.",
    shortDescription:
      "Leverage technology to improve health and wellness solutions.",
    category: "Health",
    subCategory: "Digital Health",
    instructorId: "instructor-21",
    status: "PUBLISHED",
    skills: [
      "Health Tech",
      "App Development",
      "Data Analytics",
      "User Experience",
      "Privacy & Security",
    ],
    conceptsLearned: [
      "Telemedicine platforms",
      "Wearable tech",
      "Health data analytics",
      "Patient engagement",
      "HIPAA compliance",
    ],
    estimatedTime: 28,
    targetLevel: "Intermediate",
    enrolledNum: 650,
    rating: 4.7,
    price: 119.99,
    prerequisites: ["Basic Programming Knowledge", "Healthcare Basics"],
    languages: ["English"],
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2025-09-10T00:00:00Z",
    instructor: {
      id: 21,
      firebaseId: "firebase-21",
      firstname: "Kevin",
      lastname: "Nguyen",
      email: "kevin.nguyen@example.com",
      globalRole: "INSTRUCTOR",
      profilePicture: null,
      bio: null,
      status: "active",
      createdAt: "2025-09-10T00:00:00Z",
      updatedAt: "2025-09-10T00:00:00Z",
    },
  },
];
